import { Bold } from "lucide-react";
import React from "react";

const PrivacyPolicy = () => {
  return (
    <div style={{ textAlign: "center", maxWidth: "800px", margin: "0 auto", padding: "20px" }}>
      <h1> <b>Privacy Policy</b></h1>
      <p>Last updated: March 01, 2025</p>
      <p style={{textAlign:"left"}}>
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p style={{textAlign:"left"}}>
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy. This Privacy Policy has been created
        with the help of the Free Privacy Policy Generator.
      </p>
      <br />
      <h2 style={{textAlign:"left"}}><b>Interpretation and Definitions</b></h2>
      <h3 style={{textAlign:"left"}}><b>Interpretation:</b></h3>
      <p style={{textAlign:"left"}}>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>
      <br />
      <h3 style={{textAlign:"left"}}><b>Definitions:</b></h3>

      <p style={{textAlign:"left"}}>For the purposes of this Privacy Policy:</p>
      <ul style={{ textAlign: "left", listStylePosition: "inside" }}>
        <li>
          <p>
            <strong>Account</strong> means a unique account created for You to
            access our Service or parts of our Service.
          </p>
        </li>
        <li>
          <p>
            <strong>Affiliate</strong> means an entity that controls, is
            controlled by or is under common control with a party, where "control"
            means ownership of 50% or more of the shares, equity interest or other
            securities entitled to vote for election of directors or other managing
            authority.
          </p>
        </li>
        <li>
          <p>
            <strong>Company</strong> (referred to as either "the Company", "We",
            "Us" or "Our" in this Agreement) refers to CrisisCare, Bharatpur,
            Chitwan, Nepal.
          </p>
        </li>
        <li>
          <p><strong>Country</strong> refers to: Nepal</p>
        </li>
        <li>
          <p>
            <strong>Device</strong> means any device that can access the Service
            such as a computer, a cellphone or a digital tablet.
          </p>
        </li>
        <li>
          <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
        </li>
        <li>
          <p><strong>Service</strong> refers to the Website.</p>
        </li>
        <li>
          <p>
            <strong>Service Provider</strong> means any natural or legal person
            who processes the data on behalf of the Company. It refers to third-party
            companies or individuals employed by the Company to facilitate the
            Service, to provide the Service on behalf of the Company, to perform
            services related to the Service or to assist the Company in analyzing
            how the Service is used.
          </p>
        </li>
        <li>
          <p>
            <strong>Third-party Social Media Service</strong> refers to any
            website or any social network website through which a User can log in
            or create an account to use the Service.
          </p>
        </li>
        <li>
          <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
        </li>
        <li>
          <p><strong>Website</strong> refers to CrisisCare, accessible from 192.168.1.150:5173</p>
        </li>
        <li>
          <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
        </li>
      </ul>
    <br></br>
      <h2 style={{textAlign:"left"}}><b>Collecting and Using Your Personal Data</b></h2>
      <h3 style={{textAlign:"left"}}>Types of Data Collected:</h3>
      <br />
      <h4 style={{textAlign:"left"}}><b>Personal Data:</b></h4>
      <p style={{textAlign:"left"}}>
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is not
        limited to:
      </p>
      <ul style={{ textAlign: "left", listStylePosition: "inside" }}>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
        <li>Usage Data</li>
      </ul>
      <br></br>
      <h4 style={{textAlign:"left"}}><b>Usage Data:</b></h4>
      <p style={{textAlign:"left"}}>Usage Data is collected automatically when using the Service.</p>
      <p style={{textAlign:"left"}}>
        Usage Data may include information such as Your Device's Internet Protocol
        address (e.g. IP address), browser type, browser version, the pages of
        our Service that You visit, the time and date of Your visit, the time spent
        on those pages, unique device identifiers and other diagnostic data.
      </p>
      <p style={{textAlign:"left"}}>
        When You access the Service by or through a mobile device, We may collect
        certain information automatically, including, but not limited to, the type
        of mobile device You use, Your mobile device unique ID, the IP address of
        Your mobile device, Your mobile operating system, the type of mobile
        Internet browser You use, unique device identifiers and other diagnostic
        data.
      </p>
      <p style={{textAlign:"left"}}>
        We may also collect information that Your browser sends whenever You visit
        our Service or when You access the Service by or through a mobile device.
      </p>
      <br />
      <h4 style={{textAlign:"left"}}><b>Information from Third-Party Social Media Services</b></h4>
      <p style={{textAlign:"left"}}>
        The Company allows You to create an account and log in to use the Service
        through the following Third-party Social Media Services:
      </p>
      <ul style={{ textAlign: "left", listStylePosition: "inside",  }}>
        <li>Google</li>
        <li>Facebook</li>
        <li>Instagram</li>
        <li>Twitter</li>
        <li>LinkedIn</li>
      </ul>
      <br />
      <p style={{textAlign:"left"}}>
        If You decide to register through or otherwise grant us access to a
        Third-Party Social Media Service, We may collect Personal data that is
        already associated with Your Third-Party Social Media Service's account,
        such as Your name, Your email address, Your activities or Your contact
        list associated with that account.
      </p>
      <p style={{textAlign:"left"}}>
        You may also have the option of sharing additional information with the
        Company through Your Third-Party Social Media Service's account. If You
        choose to provide such information and Personal Data, during registration
        or otherwise, You are giving the Company permission to use, share, and
        store it in a manner consistent with this Privacy Policy.
      </p>
     
    </div>
  );
};

export default PrivacyPolicy;