"""Add title and description to requests

Revision ID: 6a52f6ce91e5
Revises: 67fe1689f226
Create Date: 2025-02-28 22:40:43.680949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a52f6ce91e5'
down_revision: Union[str, None] = '67fe1689f226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
